[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

# Fixes the screenwipe crash
[[patches]]
[patches.regex]
target = 'functions/button_callbacks.lua'
pattern = '''(G\.FUNCS\.wipe_off = function\(\)[\s\S]*?)(delay\(0\.3\))([\s\S]*?)(G\.screenwipe\.children\.particles\.max)([\s\S]*?)(if G\.screenwipecard then)([\s\S]*?)(G\.screenwipe\.children\.particles:remove)'''
position = 'at'
payload = '''$1
      delay(0.3)
      if not G.screenwipe then return true end
      $4 $5
      if not G.screenwipe then return true end
      $6
      $7
      if not G.screenwipe then return true end
      G.screenwipe.children.particles:remove'''
match_indent = true
times = 1