[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

# Modifies Galdur's main UI creation function to add conditionals to galdur pages and remove caching (so the conditionals can change every time the menu is opened instead of just on load)
[[patches]]
[patches.regex]
target = '=[SMODS galdur "galdur.lua"]'
pattern = '''function G\.UIDEF\.run_setup_option_new_model\(type\)([\s\S]*?)(table\.insert\(Galdur\.run_setup\.pages, args\))([\s\S]*?)(Galdur\.pages_to_add = \{\})([\s\S]*?)(G\.SETTINGS\.current_setup = type)([\s\S]*?)(Galdur\.run_setup\.pages\.next_button = localize\(Galdur\.run_setup\.pages\[2\]\.name\) \.\. ' >')([\s\S]*?)(button = 'deck_select_next', colour = G\.C\.BLUE,)([\s\S]*?)(button = 'quick_start', colour = G\.C\.ORANGE,)([\s\S]*?)[ ]*return t'''
position = 'at'
payload = '''function G.UIDEF.run_setup_option_new_model(t)
    Galdur.run_setup.pages = {}$1
            if (type(args.condition) == "function" and args.condition()) or type(args.condition) ~= "function" then
                table.insert(Galdur.run_setup.pages, args)
            end$3
    $5
    G.SETTINGS.current_setup = t$7
    Galdur.run_setup.pages.next_button = Galdur.run_setup.current_page == #Galdur.run_setup.pages and localize('gald_play') or localize(Galdur.run_setup.pages[Galdur.run_setup.current_page+1].name) .. ' >'$9
                        button = 'deck_select_next', colour = G.C.BLUE, func = 'galdur_next_page_btn',$11
                        button = 'quick_start', colour = G.C.ORANGE, func = 'galdur_last_run_btn', $13
    return t'''
match_indent = true
times = 1